# Generated by Django 5.1.1 on 2024-12-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reviews_rating_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='available_room',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='86EAE27235EC', editable=False, max_length=12),
        ),
    ]
